[package]
name = "opds-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
httpmock = "0.6.7"
reqwest = "0.11.18"
tokio = "1.28.2"
